### PR TITLE
Attempted macOS AArch64 support

### LINKED ISSUE #687: Game crashes on startup on M2 mac
### What you were trying to do

I downloaded the game using Steam on macos 13.5.2 (M2 mac). Then I clicked Play.

### What actually happened

After starting, nothing happens. Looking in the game directory, I found a crash log (see below).

### How to reproduce

_No response_

### Game version

2.1.0

### Log details

```
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx-box2d64.dylib' for target: Mac OS X, 64-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:120)
        at com.badlogic.gdx.physics.box2d.Box2D.init(Box2D.java:32)
        at org.destinationsol.SolApplication.<init>(SolApplication.java:132)
        at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:135)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/lw/33dwv_5s409dw0y3xy6_s71n0828yj/T/libgdx<MY_USER>/d01668c7/libgdx-box2d64.dylib
        at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:316)
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:116)
        ... 3 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/lw/33dwv_5s409dw0y3xy6_s71n0828yj/T/libgdx<MY_USER>/d01668c7/libgdx-box2d64.dylib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2408)
        at java.base/java.lang.Runtime.load0(Runtime.java:785)
        at java.base/java.lang.System.load(System.java:2011)
        at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:322)
        at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:291)
        ... 4 more
```

### Operating System

MacOS

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by BenjaminAmos**
# Description
This pull request attempts to add support for macOS on AArch64 devices (M1/M2 macs). The appropriate native JREs should now be downloaded for this architecture and bundled with the game distribution. This should fix #687.

# Testing
- Build a new distribution with `gradlew distZipBundleJREs`.
- Unzip the distribution on a AArch64 macOS device (M1/M2 mac) and run it with `./solOSX.sh`.
- You should be able to play through the game's tutorial in its entirety.

# Notes
- This depends on #688.
- These changes are untested, as I do not possess an AArch64 mac to test with.

### CODE REVIEW

File: launcher/solOSX.sh [hunk 1]
```diff
@@ -1,2 +1,14 @@
 #!/usr/bin/env bash
-lwjreOSX/bin/java -XstartOnFirstThread -jar libs/solDesktop.jar -noSplash
+
+JRE=lwjreOSX/bin/java
+ARCH=$(uname -m)
+if [[ "$ARCH" == "x86_64" ]]; then
+  JRE=lwjreOSX/bin/java
+elif [[ "$ARCH" == "arm64" ]]; then
+  JRE=lwjreOSArm/bin/java
```
Comment (hesselink) [inline launcher/solOSX.sh]: There's a typo here, the directory should be `lwjreOSXArm`

Comment (BenjaminAmos) [reply launcher/solOSX.sh]: I've corrected it. Thanks for letting me know.

**Comment by BenjaminAmos** [comment]
As I've tested this manually on Windows, macOS and Android, I'm confident that this is relatively safe to merge. Two people using M1 macs have confirmed that it works for them.
